### ISSUE TITLE
Do you know about the findshlibs crate?

### ISSUE THREAD

**Issue by bjorn3** [vext01/phdrs#1]
https://github.com/gimli-rs/findshlibs

It does the same think I think this would eventually do.

**Comment by vext01** [comment]
I didn't, however, the addresses we are interested in will typically not be in shared libs, but rather in the "main" object segment. It sounds like findshlibs only does dynamically linked objects?

(btw, the main repo for this is https://github.com/softdevteam/phdrs)

**Comment by bjorn3** [comment]
A dynamically linked executable is technically a shared library too on Linux and macOS. It just has an extra command telling the OS to run a certain command (the dynamic linker) when trying to execute it. findshlibs returns an empty name for the main executable if I remember correctly.

**Comment by vext01** [comment]
I've just tried the example. On a linux machine, the main binary shows up like this:
```
/home/vext01/fs/target/debug/fs
    0x560ee49d0040: segment PHDR
    0x560ee49d02e0: segment INTERP
    0x560ee49d0000: segment LOAD
    0x560ee49d5000: segment LOAD
    0x560ee49fd000: segment LOAD
    0x560ee4a0a900: segment LOAD
    0x560ee4a0c488: segment DYNAMIC
    0x560ee49d02fc: segment NOTE
    0x560ee4a0a900: segment TLS
    0x560ee4a013ec: segment GNU_EH_FRAME
    0x560ee49d0000: segment GNU_STACK
    0x560ee4a0a900: segment GNU_RELRO
```

But on OpenBSD the iterator is empty! Sounds like a bug!

**Comment by bjorn3** [comment]
> (btw, the main repo for this is https://github.com/softdevteam/phdrs)

That explain why this repo is empty :)

**Comment by vext01** [comment]
Ah:
> These are the OSes that findshlibs currently supports:
> Linux
> macOS

**Comment by bjorn3** [comment]
I think it would be easy to implement OpenBSD support. Maybe even just changing some `#[cfg]`. Can you open an issue?

**Comment by vext01** [comment]
Sure. We don't actually *need* bsd support just now, but it's just what I run on my desktop, and was thus my first test target ;)

**Comment by vext01** [comment]
https://github.com/gimli-rs/findshlibs/issues/45

**Comment by bjorn3** [comment]
Thanks. Should this issue be closed?
